import type { Metadata } from "next";
<<<<<<< HEAD
import { Geist, Geist_Mono } from "next/font/google";
=======
>>>>>>> 978af04 (Initial commit)
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";



<<<<<<< HEAD
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

=======
>>>>>>> 978af04 (Initial commit)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/" >
      <html lang="en">
        <body
<<<<<<< HEAD
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
=======
>>>>>>> 978af04 (Initial commit)
          >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
